In [ ]:
#
# 生成训练数据(GenTrainingData)：
#

# -*- coding:utf-8 -*-
import os
import tensorflow as tf
import numpy as np
from PIL import Image
import shutil
import pandas as pd
import cv2
from math import *

# 生成字典文件: 或者用ord(), chr()函数进行整数和中文转换，缺点是数字太大，不连续!
def CreateDict(dictList, dictFileName):
    # fp = open(dictFileName, 'w', encoding='utf-8')
    fp = open(dictFileName, "w+")
    for x, word in enumerate(dictList):
        if dictList[x] != '\n':
            fp.write(dictList[x])
            fp.write("\n")
    return

# 找到单个文字对应的编码：
def GetCharCode(dictList, char):
    x = 0

    if len(char) == 0:
        print("Error: char is none ",char)
        return None

    # 当dictList为空时：避免enumerate报错！
    if len(dictList) == 0:
        dictList.append(char)
        return 0

    for x, ch in enumerate(dictList):
        if dictList[x] == char:
            return x

    # 没有找到，则添加到末尾：
    dictList.append(char)
    # print("Not Found: [", char, "]")
    return x+1

#
# 添加图片文件名和内容到标签文件
# destdir\label.txt: item.filename item.content
#
def InsertLabelItem(dictList, item, destDir, lableFile):
    # print(filename, content)
    oneitem = item[0] + ".jpg"       # item.filename
    # full_lablefile = os.path.join(destDir, lableFile)
    fp = open(lableFile, "a+")
    
    for ch in enumerate(item[1]):       # item.content
        code = GetCharCode(dictList, ch[1])       # 得到对应的编号ch[1]
        oneitem = oneitem + " " + str(code)
        
    oneitem = oneitem + "\n" 
    fp.write(oneitem)
    fp.close()
    
#
# 将图片文件转换TFRecord格式：
#
#def Data2TFRecord(images, labels, filename):
def Data2TFRecord(picPath, lableName, recName):

    if os.path.isfile(recName):
        print("%s exists, now deleted!" % recName)
        os.remove(recName)

    labels = []
    images = []

    #for i,file_path in enumerate(file_path_list):
    train_txt = open(lableName)

    for idx in train_txt:
        idx = idx.rstrip("\n")
        spt = idx.split(' ')
        images.append(os.path.join(picPath, spt[0]))
        labels.append(spt[1:])
    
    #print("FILES: ", images[0:10])
    #print("LABEL[0]: ", labels[0:10])
    print("Converting data into %s ..." % recName)
    cwd = os.getcwd()

    writer = tf.python_io.TFRecordWriter(recName)

    for index, img_name in enumerate(images):
#         img = Image.open(img_name)
#         img = img.convert('L')

#         # 调整大小为统一尺寸：
#         img = img.resize((280, 32))
#         img_raw = img.tobytes()
        
##################分割线   如果宽度小于高度，则旋转90度，不能使用PIL的rotate函数（会导致信息缺失）
        img = cv2.imread(img_name, cv2.IMREAD_GRAYSCALE)
        height,width = img.shape[:2]
        if(width < height):
            degree = 90
            heightNew = int(width*fabs(sin(radians(degree)))+height*fabs(cos(radians(degree))))
            widthNew = int(height*fabs(sin(radians(degree)))+width*fabs(cos(radians(degree))))
            matRotation=cv2.getRotationMatrix2D((width/2,height/2),degree,1)
            matRotation[0,2]+=(widthNew-width)/2
            matRotation[1,2]+=(heightNew-height)/2
            img=cv2.warpAffine(img,matRotation,(widthNew,heightNew),borderValue=(255,255,255))
        cv2.imwrite('./tmp.jpg', img, params=None)
        # plt.imshow(img,cmap='gray')

        img2 = Image.open('./tmp.jpg').convert('RGB')#直接转L模式有错？
        img2 = img2.convert('L')
        img2 = img2.resize((280, 32))
        img_raw = img2.tobytes()
##################分割线 
        label = np.asarray(labels[index], dtype=np.int64)
        print(label)
        
        if len(label) < 30: 
            example = tf.train.Example(features=tf.train.Features(feature={
                    'label': tf.train.Feature(int64_list=tf.train.Int64List(value=label)),
                    'img_raw': tf.train.Feature(bytes_list=tf.train.BytesList(value=[img_raw])),      # [img_raw]表示为[280,32,1],只考虑1个通道
                }))
        
            writer.write(example.SerializeToString())  # Serialize To String
        
    writer.close()
    
    print("Convert finished!")
    return

# 读取目录及子目录下所有文件：拷贝到指定文件夹

def GenTrainingData(dictList, picDir, destDir, lableFile, recName):
    # 删除目标目录下所有文件：
    if os.path.isfile(recName):
        print("%s exists, now deleted!" % recName)
        os.remove(recName)

    if os.path.isfile(lableFile):
        print("%s exists, now deleted!" % lableFile)
        os.remove(lableFile)
        

    #dataset = pd.read_csv("./data/problem3/content_train.csv", nrows=50)
    dataset = pd.read_csv("./data/problem3/content_train.csv")
    
    # 总行数：
    num = int(dataset.size/2)
    print("Total rows: ", num)
    
    filenames = dataset.iloc[ : , :].values
    
    for i in range(num):
        #print(filenames[i][0], filenames[i][1])
        InsertLabelItem(dictList, [filenames[i][0], filenames[i][1]], destDir, lableFile)
    
    # 生成代码表：
    CreateDict(dictList, './training_data/ocr_char.txt')
    
    # 生成TFRecord：
    Data2TFRecord('./data/problem3/train',lableFile, recName)

    return
dictList = []
GenTrainingData(dictList, './data/problem3/train/', './training_data','./training_data/label_convert.txt', './training_data/ocr_convert.tfrecords')

Total rows:  26439
Converting data into ./training_data/ocr_convert.tfrecords ...
[0 1]
[2 3 4 5 6 7]
[8 9]
[10 11 12 13 14]
[15  0 16 17 18 19]
[20 21 22 23 24 25]
[26 27 28 29 30 31 32 33 34]
[35 36 37 38]
[39 40 41 42]
[43  0 44 45]
[46 47 48]
[24 49 50 51 52 53]
[54 55 56 57 58 59 60 61 62 63 64 65 66 67]
[68 69 70]
[71 72]
[73 74 75 75 76 77 78 79 80 77 76 79 74 81]
[82 83 84]
[85 86]
[87 88]
[89 90]
[91 92 93 94]
[95 73 72 78 74 77 75 96 97 98]
[ 99 100]
[101  55 102 103 104 105 106]
[107 108 109 110 111 112 113 114 112 115 116  64  65  66  67]
[117 118 119 120  39 121 122]
[123 124]
[125 126  17 127]
[ 85 128 128 128 129 129 129   8]
[  8  86   8 128 130 131 131 129 129 129   9]
[132 133 134  34 135  30 136 133 137 138 139]
[140 141 142 143]
[  8  86  85  85  86 144  85 129 131 130   9]
[  0 145]
[146  81  79  79]
[ 85 147]
[ 66  35 148 149]
[ 85   9   9   9 150 130   9   9   9 151]
[131   9 152]
[153 154  11  62 155  42]
[144   9]
[108 111 156 157]
[ 44 158]
[159 160 109 161]
[

[728 289 167 168 450 240 729 730]
[ 98 196 195 190 282 189 475 190 281]
[731 732 346 101 111 683 733 609 295 734 735 247 736 737 738]
[439 614 507]
[739 740]
[741 498 742]
[  9 128]
[ 15 239 321 290 177]
[743 646  44 155 744]
[550  62 177 745]
[746]
[747 482 748 749  37 750]
[ 17 412 203  93 240]
[130 128   9]
[ 73 280 357 566  71 566]
[379 751 752]
[121 753 754]
[755 290]
[  8 131 130  86 129   9  86   9 131 131 130]
[550 129   8 359 317 491 130 129 359 317 756 258 359 317]
[155]
[711 475 476 189  77  81 282]
[321 116 757 477]
[642 379 758]
[ 70 640 257 759 412 118 760  59 761 321 165 295  11 762 378 295 763 215
 467 744 258 764  95  63 215  70 531]
[  8  86 258 129  85   8 129 129 129 129]
[ 74  74 765 709]
[181 182 346  99]
[666 667]
[91 92]
[166 766 767   5 768 166 612 769 156 770]
[131   4]
[144 130  85   9   9   9   9]
[  8 130  85 144 129   8 129 258 131 129 130]
[269 771]
[345 184 125  65 274 529 119 772 773]
[774 421]
[533 380]
[775 340 257 121 776 305  84 520 777 377 520 300 

[367 368 369 370]
[193 194 281 549]
[1040  576  123  470  790 1041  240]
[122 655 643 901]
[1042 1043  884  378 1044]
[ 439 1045  956  319  217]
[553 168 572 776]
[1002 1046]
[ 450  120  502  109 1047  987 1048 1049  741  579]
[ 249  794 1050  241]
[35 36 37 38]
[ 141 1051  181    4  257  484  475  361  192  193   77  194  192  549
  195  194  195  190  193  189  193]
[ 589  433   27  556 1052 1012  487  218  382]
[ 97 317 475 196 188 549 194 281 190 195  77 147 475 359 188 281 196 476
 193 194 281 549]
[ 451  325  379  257 1053  710]
[484 189 282 195 475]
[ 123  470 1054 1055]
[1012  493 1056  564]
[538  17  39 560 443 645  14]
[ 49 455 569]
[ 756 1057]
[350  96  77 484  96  81  79]
[1012]
[ 101  216  204  886  773 1058   48  270  200 1059   36  204  379  246
  184 1014  197  231]
[  8 130   9   8 130 129 128 130 144  85   9]
[ 24  49  93 354]
[ 147  196  281 1060  195  190]
[484  72  97  73 219  72  76 219  74  78 150 173  96  96 350]
[711 219 220 220]
[ 859  363  241 1061 1062 1063]

[ 107  108 1227 1228]
[ 73 711 357]
[ 131  151  913 1229]
[1230  500]
[ 765 1092  839  503]
[ 653   30 1231 1232 1233 1234  479  385  240  311   40]
[ 160   66   67  165  830 1235  618   30   43  381  175  384  272  790
  820  379  169]
[1236 1237 1238]
[ 24  49 790 275 692 608]
[346 619 234 518  83 379 315 349 230]
[1239  936  496]
[  98  194  195  196  195   77  189  193   77  475   77 1070  475  476
   77  281  192  188]
[367 368 369 370]
[131]
[  62 1240  707  290]
[146  81  79  79]
[711 196 189 282 191 195]
[521  93 354 109  70 315 602 379]
[ 24  49  93 354]
[ 93 354  49 455 439 291]
[1112  412  111  421]
[193 317 189 361 195 193]
[1241 1242  206  727]
[159 313 330]
[1243  948  797 1244]
[ 452 1245   57]
[ 159 1246  107]
[1247  444]
[ 110  153 1248  380]
[459 460]
[549 361 475 476 193 189 190 191]
[  8  85 498  85 144 499]
[1223  535 1249 1250  683 1251  861]
[487  33 868]
[1252 1253 1254]
[895]
[201]
[313 377 497 204]
[1255  137  858]
[258   9]
[ 373  301  204  957  577    5  336

[450 109 102]
[ 702 1147   99  100]
[1372 1373  376  569]
[391 128]
[ 96  81  72  79  78  98  77  81  72  97  72  78 146  77  97 219  78  77
  98  79 220  79  95  96 484]
[637  25]
[  39  805  573 1374  210  474]
[250 776 376 552  52  53]
[427 148 516]
[223   5 634]
[71 72 76]
[496 488 562 928]
[1375  330    8 1376]
[ 24  49 957 168 692 608]
[ 85   9   8 131]
[558  28]
[739 740 428 429]
[518 559]
[101 216 437 273 378 612 916  24  25]
[  9 129  86 128  86 131]
[ 118 1377  517  569]
[  8 130 131  85 258  86  86   8   9   8   9]
[   5 1378  611  433]
[722]
[255   4 106]
[ 885 1046  692  608  319  481  168  708  709]
[495 496 497 204]
[   5  691 1223  897]
[1379 1380  257  261  489]
[1381  556 1382 1383   30 1384 1385  505  865]
[ 313 1121]
[ 274 1331 1131]
[980 802 439 291]
[ 159   49 1265  168]
[102  60 408  63 450]
[989]
[1386  789  217  166 1387  131    9    9  150   86    9    9  151   77
 1388  643   86    9    9  150    8   85    9    9  151]
[790 820]
[463 464 295]
[ 382 1389  184 

[1417  630  532 1488]
[365 458 166 612]
[701  78  78  77  97 475 361 195]
[ 373  301  204 1332   66   67]
[618 449 414   4 251]
[249 596 337   5]
[479 827  27]
[ 127  537  257 1252  519]
[218 157 439 414]
[1489 1490 1394  962  679 1304   45  679 1491  896]
[549]
[379 246 166 953  31  40]
[ 335  283 1064  125 1137   64]
[ 101  216  204  645   14  295  235 1008  507    8  144  130  150    8
  215]
[ 96 549 195 190]
[566 195 195 549]
[ 491  914 1365  482   56  689  662  663   34]
[ 24  25 315  24  25]
[1492   14  748]
[ 134 1493  875 1494  632  311]
[ 37 311  15 239 619]
[ 97  74 220  79]
[357 195 190 195 146 195 195]
[492]
[596]
[1272 1075  126]
[394 518]
[1495  165  229]
[1496  298]
[ 101  216   24  455 1374  689  266 1418 1383  750]
[  21  907 1097   57  231  378]
[ 98  74  72 220  96  81  79 350  77 173  96  81  77  74  77 173  81  72
  79  78 350  77  96 173]
[ 346  619  376  177  380    5  184  313   37 1312 1497  396  599  898]
[1492 1498  518 1499]
[ 24 870  49 606  80  95  72  98

[ 553  168  539 1594]
[350  96  78 350  79  77  72  78  98  79  81  78  74  98  72  96  78  74
 220  77 146  74  81 350  79  78]
[  8 131  86 151]
[343]
[ 502 1570 1595  916 1596  370 1597]
[711 361 475 359 717 147 189 193 194  77 484 192 193 195 192]
[ 900 1389  378  800  168]
[773 335 336 790 607]
[ 28 908 230]
[770 387]
[549 189 359 359]
[612 516  43 521]
[ 363  364  365  315 1598 1599]
[246 602]
[  8 107 129  74]
[642 937  62 102 639 395]
[ 72 484  74 391]
[437  99]
[1155  181   24  217 1270 1374   64  241]
[ 210  377 1600 1434]
[123 470 257   8  86 130 258 129 129 130 258 129 128 130]
[609 477 602 828 300  25 496 133 987]
[ 373  301 1343  518 1306  339  798   22]
[ 201   91 1334  872  435  333 1334  872]
[ 80 192 194 475 190  77 195 475 193 188  77 361 475 717 195]
[  8  77 614 855]
[ 461   47   40  364  319  315   38 1197 1325 1601]
[1602  227  672]
[137 159 616 983]
[258 173]
[397 794 393 264  84 155 165 157  70]
[711  95]
[ 397  794   49  482 1179   70   66  378]
[1603  212    

[ 201 1294  841   85    9    8  128  433  483  433  111  261  316   25]
[166 953  31 756 125]
[117 110 433 379 666 667 699 462]
[  88  262  529  208  468  536 1453  176  213   24]
[500 375  21  97  75  74 210 248 231 378]
[  8  86   8  86 130 131 131 129 129 129   9]
[ 122  690  829  669 1674  464 1136]
[ 373  301  204  206 1281  482  757  477  572  106  803  804  815   70]
[  40 1592  252   40  204  481  168]
[1264]
[ 916  829 1055  290]
[ 725  408 1675 1009  496]
[667 289   2 903]
[185 470 113]
[91 92 93 94]
[467 421  38  70 531  95  37  38]
[ 583  272 1676  642]
[1239  337]
[  24 1578  153  477  295]
[ 36  49 428 429 257 144   9   9  86 131 131  85  85 128   9]
[ 64 482]
[ 741 1130  390 1131 1344]
[249 433 737 862]
[1009  433]
[74]
[1093  668]
[1482  166 1024  427]
[  43    0 1037  134 1677]
[ 428 1678  916]
[642 325 957 668 247 248]
[1679  380  207]
[1097   57  389  790 1041]
[253 440]
[144 130 130   9   9   9]
[1272 1680  241  151]
[ 97  73 219  72]
[137 363 612]
[121 460 105 276]

[ 228 1734]
[739 740 105 276 732]
[ 81 189 282 195  77  73 195 196 195  77 188 281  77 146 361 475 359 189
 195 196  77  75 475 196 717]
[1037  137 1735]
[1605  916   98 1736]
[ 9 74]
[255 253  56 256]
[81]
[1737  427  379  166]
[ 408 1007  614  855]
[ 99 269]
[1280  820 1495  482   30  820  482   30  379  420  941 1738 1106  241
  637  315  737  687  726  231  379]
[317 475 188 189 361 475 190 282]
[68 38]
[1213  482 1728  168   77  482  921  773  338]
[452 278]
[711]
[351  96  81  96  77 484  96 350]
[ 66 208]
[1438   27  383  263  383  240]
[1055  903   37  371]
[ 843 1516 1212  166  262    5]
[1739 1445 1647   21  907 1097   57  231  378]
[1690   30  669 1023 1740  450   30  118  401  771 1741]
[ 38 829 344 643]
[1389  210 1112  612]
[35]
[ 81 281 190 193 194 195 190]
[ 134  617  335 1366  629  404  428 1531  655]
[191 195 361 475 188 281]
[449]
[ 632 1742  502  421]
[ 272 1481  155]
[141]
[  54  390 1516]
[ 48 270  66  67]
[ 932  499 1743]
[86 86 86 86  8]
[ 689 1333]
[131  85]
[ 

[531  28 128   9 128 131   9]
[ 658 1162]
[1602  284]
[432 936 428 429 257   9  85 129 131 258   8   9   8  86   8  86]
[941 229 477 750]
[ 385  240   85  498  144  499  292   85  498    8  131  499  186 1206]
[1460 1288  479 1464  435  363  678 1416 1162  409  742  404]
[ 666  667 1081 1052  117  110  433  379  699  462]
[  8 131]
[454 498  56 663 404]
[ 40 487 687 506]
[123 733 101 111]
[ 11 284]
[482 302]
[181 182]
[609 295 921 246 821 169 477]
[155]
[699  38]
[  8 130 129 129  86 258  86 129  85   9   8]
[201]
[317 195 317]
[218]
[209 123 903]
[  68 1200]
[1609  421]
[  91   92 1066  262]
[350 701]
[  85   85    9  191  187   85  144 1627]
[1623  786  279]
[335 336   8   9 151]
[  9 129]
[ 61  62 295 379 246 886 812  85   9   8 131 433 128 498 130   9 499]
[711 220 350]
[ 729 1807 1115  709   36  662  663]
[ 36 482 284  34 135]
[1808]
[1809  210  494]
[95 74 81 98 74 97]
[146  96 484  79]
[95 73 72 78 74 75 96 97 98]
[ 85 144 194]
[173 219  77 566  72  74  77  73  96  98  79 220]
[

[1134  694   39   40   41   42]
[488 690]
[ 379  166  364  111  315 1413  307  363 1334  872  310]
[ 439 1303  514 1875  593  768  137  346  514 1875 1876]
[653 654  45]
[1877]
[510 183 379 482  91  92 234]
[255 253 463 464 262 783]
[517 343  28 617]
[385 240 425 644]
[191 475 361 475 187 476  77  74  86]
[131   9]
[364  20]
[   2    3  472  207 1059  234  518  234  315   17  699  349  230  316
  495   35]
[131]
[920 482 525 748]
[ 75 361 195 475 193 195  77 722 195  77 359 475 196 195 147 192 361  77
 281 147  77 193 188 475 189 196 359 475 193 195  77 193 361 189 188]
[756  24]
[992 723]
[ 88 262]
[1878 1515 1879]
[1100  416 1100]
[ 24 178 102 179]
[203]
[167 168   2 903]
[262 227 690 159]
[129 130 129]
[ 50 376]
[ 905 1717  687  303 1822]
[130   9 484]
[ 98 194 195  77  78  72 357  79  77 173  81  79  79  77 131 280   9]
[271 272   5 691]
[  85    9    9    8  433   30  670  246  921  395  452   35  204  379
  246  886  812   66  962  346  725  408 1069]
[934 479 316  64 444 968 120

[ 159 1943   56  916  290]
[ 95 475 147 147 195]
[91 92 93 94]
[799 140]
[86]
[ 185  343  616  630 1123 1254]
[ 560  443  319  850 1114   68  502  421]
[ 80 189 190 282 189 190 191  77  79 317 722 475 190 717 317 195 190 188]
[187 194 130   9   9]
[1159  353 1654  908]
[ 74 130]
[ 863 1145]
[  93 1653   40  274]
[ 550   35 1944 1274 1879]
[  9 280 131 151]
[ 433  156 1065 1301]
[ 64 574 431  41 433]
[350  74  75  73  78  79]
[247]
[429 428 276 105 783 104]
[220 476 281 359 195 361 361]
[522 117 311 396 916 577]
[ 98 281 189 361 195 188]
[  0  28  23 168]
[146  81  79  79]
[129 498]
[ 246  275  596  679 1945  596  679  608  886  679  487  596  487  275
 1789  320    6  213]
[1115 1625  227   43   24   49  389  409  742  916  690]
[1946 1947]
[ 144   85 1216  294  756]
[ 80 195 189 282 192 281 361 189  77 711 192 189 361 282 189 190 191]
[141]
[493 484 386 484 129  86  86 129]
[ 823  824  594  210 1725 1725  315]
[ 335 1023]
[167 569 376 349 337   5]
[ 468  454    6  679  590  468  471 1

[73 96 78]
[ 214  512  243 1446]
[283 230  99 100]
[ 88 532 168  60 411 412  63  64  65  66  67]
[ 932 1320  286]
[ 70 640 257 373 301 101 275   7 273  24  25  86 173]
[92 93 94]
[702 424]
[1228  838  625  428 1795   64   65   66   67]
[ 75  81  79 173  79  81  81  79 350  77 484  79  81  95  73  74  78  98]
[1436  278   56  256  257    8  131  130   85  129  144   85  258]
[85]
[992 181   4 484 475 189 282 195 190  77  73 475 189 196  77  98 196 195
 195]
[1897  284]
[  8 258 131 258 386  54  49]
[184  40 204]
[75]
[  8 280  85 317]
[108 579 454   6]
[81]
[1987  954  892  316  316  316]
[  39  805  806 1833]
[453]
[121 837]
[1392  412  204   70 1818  504]
[687 343 525 109 272]
[146  81  79  79]
[377 616]
[1176  278  277  278  128  151  199]
[626 608]
[1785  576  344   34 1440  592]
[1014  709 1279  425]
[369 503 197]
[81]
[ 765  692 1027]
[95  8  9 85]
[  9   9 144]
[1265  401  159  401]
[ 95 220]
[ 56 916 790 302]
[1270  258]
[ 43 521  43 644]
[ 36 429]
[  8 131   9  85 129  85 129 1

[ 88 311 382 800 168]
[ 49 219  95  95 209 212]
[ 458 1076]
[ 73 220  74]
[847 458 848]
[ 9 85  9]
[ 95 195 190 188 195 196  77 281 147]
[1515]
[ 85 144 319   2  36 714 369 940  40 450 105 276  77   8  86 131 150  86
  86  86 131 150   8 258 258 130]
[75 72 71 71 74]
[ 411 1020 1021    7]
[715 529 128 319   2]
[ 902   88 1332 1007]
[662 765 123 610 663]
[187 128]
[ 165   43  121 1642]
[477 169 496]
[1599  409  205  853]
[ 85 144 131]
[ 980 1306  502  262  470 2024]
[ 499   60  208  498 1468  129   63  321  322   40  993   30]
[ 56 256 257   8  86   9 128  85   9   9 130 129 130 128]
[ 720  107  185 1116  295   70 2025  504]
[ 121  837  495 1034   66  208 1281  853]
[263 383 240]
[ 364 1540 1366 1735 1277 1460   24  249 1002 1046  750   64]
[ 394 1304 1490]
[144   9   9 150 128 144   8 150 258  85 258 258]
[1141  631  115  116  878  879    5  691]
[1165 1111  233]
[  8   9 258 280   9   9]
[553]
[1265   39 1766 1366]
[ 114  376  529 1454  898   43    0]
[144   9   9   9  86   9 131 129 

[ 75 196 195 193 189 282 195 190 188  77  96 147 147 189 359 195]
[ 8 86]
[ 319  409 1572]
[ 40 408  42]
[214  49 210  93 314 824]
[1205  450]
[75 74 98]
[  9  85  86 150 128   8   8   9   9   9 258]
[1722 1722 2059   30  286 1385 1114   30  505]
[209 123 903]
[1071  189  475   77  194  195   77  196  195  475  361   77  195  193
  188]
[1964 1965  111  421]
[2060 1086  482  921  105]
[ 261  372 1247  444]
[ 433   24  111 1138]
[ 117  118  227 1528]
[  56 1032  453]
[ 86 129 131 130   8   8   8 258]
[  39  805 1324  262  502  421]
[345 322 477 169]
[  40  487  502  262  638 1570]
[ 107  108 1227   43    6  247  248  217  251]
[357 189 282 193]
[ 97  78  96  80  77 484  96 219  98  74  72  78]
[ 353 1719  107  609  295  105  276  103]
[444 111 383 185 642 467]
[477]
[ 490 1154  130    9    9    9  150  128    9    9    9  151]
[1228 1671 2042  247  248  271  272  756 1029    5  691]
[ 219  190  282  195  196 1070  475  188  195  196   77   97  189  191
  194  188  193  195  195  189  19

[ 950  951  952  953 1228  273  207]
[1409]
[111 655 204  44  19 427 170 171 172  64  65  66  67]
[ 95  73  72  78  74  77  80 219  73  74  78]
[1090  378  239]
[235 236 121 250 497 204]
[ 74 566  72 350  96 219]
[725  41   4]
[ 353 1545 1131 1344]
[  24   49 1080 1096  111 1207 2101]
[94 93 92 91]
[  8   8 150   8  85]
[   1  252 1306]
[101 216 376 383 439 291]
[367 368 369 370]
[ 480 1014  518   24  114  114  238]
[345 773  36  49 181 182 714 204]
[1046 1301  616  870]
[ 991  133 1388 2102   59  761]
[  44 2103  111  421  408  988]
[1365   70  914]
[560 159 234 315 349 230]
[  24   49 1356]
[ 747  482  668  216  275 1897  939   42  258    9  144  233]
[141]
[246 166 692 608 822  37]
[  93  354   30  364 2104  166  612  315  714  204  182  741]
[1228  250  274  727]
[ 662  663 1695  987]
[ 98 484]
[85 86]
[2080  428  210 1136 1737 1917]
[ 97 219 146  74  81]
[ 80 195 193 188]
[718 790]
[544 545 546 239 331]
[343 421]
[ 321   25 1272  241  109]
[1443 1080  205  181]
[ 99 270]
[95 95 95

[184 749 493 380]
[ 24  49 564   4 275  52]
[ 98 484]
[538  18]
[2138   52]
[502 421]
[ 837  731  414  130    9 1216]
[ 95  73  72  78  74  77  97  75  96  81  98  97  77 220  96  98  98  79
  81  76]
[286 488 690]
[493 484 386  86 128  85 131 128]
[ 24  49 885 886]
[ 197 2139]
[ 411  412  204  181  273  376 1015 1055  841]
[ 39 318]
[  9  85 129 150  86 129  86 128]
[ 650  642  639  499   77   11 1002  556]
[711  73  85]
[ 742  118 1654]
[ 38 343 278 453]
[  0 343 313]
[1332 1007   19]
[  11 1459  241 1229]
[450 869  42]
[ 98  79 220 447   8 130 128  85 129  85 129 130 130   9   9]
[ 73 192 475 190 193 194 475 190  77  78 281 196 188 194  77  81 281 475
 282]
[484 195 282 189 359 189 190 195  77  73 281 193 549 189 188 475 361]
[ 701   98  220 2140  471  511  839  182]
[ 414  699 1145  790   43  291]
[ 80 220  80]
[ 208 1175  101  216  428  616  562]
[533 636]
[1797  843  396   65]
[ 953 1605  363  117  572  315]
[ 85  85 258 258 129   8]
[721 261]
[181 182 223 597]
[ 101  216  204  8

[  8  86 258   8  85 129  85  85  86  86 129 131]
[ 74 150   9   8   9]
[621  40 536]
[711  95 150 131   9  79  97]
[ 121  916   56 1032]
[ 24  49 451 502]
[711  96 391]
[297 562]
[2169  305 1636]
[550  62   4 290 477 750]
[130 130]
[1001  442   70   41  313]
[ 305   28   84   30  385  669 1602  332]
[2170 1517]
[410   5]
[692 451]
[  74 1592  602  532   40  204 2171 1475  123 1216   69  461 1228  362
 2171    8  144  433    5  336   88 1971]
[1564]
[ 80 192 194 475 190  77  79 475 193 188  77 220 475 717 195]
[ 205  366 1280  462  100 1137  940 1695 1382   30  396  820  346  618
  918  404  302  424  462  100  384  886  812 1069 1551  181  320 1280
  275    5]
[1112 1375    4  366  938  939 2000  733]
[538 365 315]
[129  86 152]
[2172  533 1252 2173  366]
[1302 1238  649]
[250  30 246 602  30 181 182 679]
[190]
[ 56 256 257   8 130 131 128   8  86 130 131 258 258 258]
[ 397   25 1133 1895   24   49  389]
[ 947  593 1915 1528 1962]
[581]
[ 180  181  182  183  184  185   77   66 1075  4

[ 107  108 1227 1634 1152  155  181  324 1418 1383  477]
[483 433 111 261]
[  17 1135  428  429  257  144    9    9   86  150  131    8  128  131
  258    8]
[ 166  577  275  257 2203 2204  204 1001  771 2205  337    5 1041]
[414 240  64 223]
[  9  86 130 130 258 128 130]
[75]
[1647  266   56 1095]
[ 79  79  77 220  96  95 357  79  81]
[456 457]
[1446  380]
[  66   28   35   36 2206 1124]
[2207]
[ 73 475 189 196  77  95 475 196 195]
[ 85   9   8   9 433 131]
[592 423 216 467]
[484  74 220  79]
[216  38 217 238]
[144]
[661 561 337 273  64 766 633 315 379]
[ 95  73  79  78 146 350 219]
[1070 1070 1070  280  189  359  722  359  280  359  281  317  280  359
  190]
[  0 990 266 665]
[439 451]
[714]
[ 98 219  81 711  96]
[  8 131  86 129   8  86  86 258 258   8 129]
[ 902 1184]
[ 322  345 1106]
[1495 1140  656  964]
[ 78 281  77 711 192 196 190 189 190 191]
[95]
[181 182]
[ 956  668  507 1672  128  215]
[609 477 602 828 300  25]
[1436]
[ 270  473  458 1076]
[2208 2209  593   49]
[  74 1592]


[484 189]
[ 95  95  81  95 714 154 569 401 609 270]
[1069  165  257 2149 1364 1399 2149 1364  302   44  623  330 2135  742
 1312]
[  40  487  502  262  638 1570]
[104 113]
[62]
[1012  493 1227   56  690   66   67]
[381 175]
[550 633  85  86  85 317]
[ 345  184 2092  916 2234  414  132  534  397 1748  165  830  184 1495]
[ 73 475 281 722 475 190 361 513]
[  8   9   9   9 317 317]
[470 916 290 502 421]
[2235  718   49  455]
[503 504 176 596 111 453]
[ 144  357 1388 1558  324]
[1428    5  732  213]
[181 153 247 248]
[ 24 736 206 896 207  91  92 234 316]
[ 182  109 1667]
[645  14 295 560  14 467 515  35 609 295 105 276 103]
[ 290 1502  973  974 1092 1882]
[ 159   54 1297]
[ 202  203  756    3  921 1134 1871 1393]
[790 820]
[78 74 78 73 74 96]
[549 361 475 476 189 190 191]
[2056  140 1865 1866  468  339  997   40   30  550 2236 1106  109   70
  903   30  125 2237  125 2193   30  363  364  346  339]
[324 158   5]
[ 95 194 189 190 475]
[9 8]
[131 173]
[1013  518  111  593]
[ 98  79 220 447   

[ 585  683  518 2084  636]
[190 475 317 359 281]
[  58 1571  975  632 2261]
[484 196  77 193 717 189 190]
[987  93 536 290   8   9 151 913 848]
[162]
[ 538  365  315  165 1840  204  291]
[ 56 256 257   8 130   8 130 131 258 258   8 129  86 131]
[ 24  49  93 354]
[ 344  345 2262  148]
[ 763  763 1213 2085  536]
[ 53 756]
[711  76 350]
[1775  204]
[  50   51  702 1025  335]
[ 461 1025  616  209]
[2263   93 1672  410]
[521 181 182  64 223 101 216 379]
[258 258]
[ 216  343 1176  106 1216  454 1023]
[1419 1015  502  421]
[1035  323]
[1265  168]
[144 280 130 855 835 835 129 280 258 855]
[1684   54  815]
[  86  131  128 1270   85    9]
[  8 258 258 131]
[483 433 435 363]
[ 202  203  204 2197 1609 1014  155 1041]
[272  64  24 647 109 753]
[ 484  359  350  281  190  475  361  282 1991  193]
[101 216 720 107]
[2264  536 1522 2265  166]
[219  81 711  74  78  77  97  98  79  81  79  96]
[ 86 129 131 130   8   8   8 258]
[  49  482  773 1895  634  410  241  534 1058  478  269]
[ 382 1983]
[ 241 178

[ 764   80 1353]
[ 457 1919  469  241  109  876   40  518  454  109 1176  278  396  618
   15]
[397 760 754]
[ 128 1127]
[ 85 280   9 317]
[72 95 79 77 98 79 74]
[  66  252  290 1279  425]
[ 81 131]
[611 111   5 691]
[170  44 155]
[111  41]
[1475  914  608  986  315  606  104]
[ 184    0 1588   19]
[146 475 196 282 195 190  77  95 194 189 190 195 193 195  77  74 359 475
 282 195 317 476  77 281 147  77  97 359 189 195 190 359 195]
[ 247  789  790 1331  217  166  612  916   24   25]
[81]
[111 656 423  66  35 503 504]
[155  42]
[ 919  517 2309 1034 1034]
[ 468  940   56   66   67 1276]
[ 866 2116]
[ 920  794  518 1499]
[  99  269 1080  158]
[  85  131    9 1270    8]
[350 475 189 566 189 190 187 189 475 190]
[81]
[1634  319 1387]
[ 101  216 1111  976 1507 1111  590  576 1540 1029   78   96  280    9
  128  764    9    9   85    8 1353]
[ 937  379 2310  921]
[  56 1672  165  182  379  159 1515  166]
[665 212 706]
[ 468  482  794  521  142  365 2063   57]
[ 756  496  765    7 1092  839  50

[665]
[643 901 380]
[1715 1716  279]
[130]
[146 195 188 188 281 549]
[ 562  870  314  824 2343 2344]
[ 457  420 1317 2345]
[ 8 85]
[202 203 204 205 206]
[275 482]
[1389   85    9  151  530   85  151]
[95 73 72 78 74]
[ 470 2024   17  790]
[461  47 714]
[ 153 2324  239  240]
[ 729  165  731  205  479  847  458  848 2346   48 1389   85    9  142
 2275]
[2347  875  770]
[2067   23 1452]
[483 433 261 372 316]
[130 129 130]
[ 85   9   9 151 258 855]
[24]
[35]
[284 315  99 343]
[937  19]
[711  74]
[  8 215 450]
[ 389  554  914 1213  482]
[451 325  56 256 128 130 144  85]
[ 24  49 885 886]
[173 219  81 219  97  72]
[875 165 348 537]
[ 125 1431 1432  502  421]
[62]
[  4 239 744]
[128 173]
[357  74  72  80  79  72  77 711 195 195 196  77  73  96 219  97  79]
[101 216 531 507 504 606 608 105 276  66  67]
[1021  608  349   24  112  207]
[ 78  96   9   9   9 128  93 354 240]
[ 121  753  502 1222]
[ 64 159]
[   8   85  498    8 1038  144  499]
[39 40 41 42]
[1274   99  348  537]
[ 714   23 1466 128

[121 460 197 278]
[1014  634 1016  320 1389  129  258  258]
[376]
[121 837]
[ 980 1608  941  229  737 2369]
[ 275  783  553  262  156 1032]
[241 142 365 499  57]
[98 79 74]
[432 936 428 429 257   9 129 131 131 150  86 128 128   8 131   8 131 131]
[  97  281  192  188  194   77   75  194  189  361  281  193  281  549
  194  189 1060  189  190  191]
[530  85 151]
[ 85   9   8 129]
[493 484  74  74  72   9 128]
[488 690]
[484  79 391  72  95  74  78 652 976 379]
[159 377 159 482]
[205]
[797 798]
[1486   93  181  302]
[209 290]
[1246   57  275  276  472  207]
[ 49  99  36  49 397 641 827 165]
[ 24 278]
[1475  123 1133]
[ 469 1094  864  113   56 1136]
[ 85  85   9 799]
[909 327]
[   8  768  286  647  690 1114   77   85  768 2370 2206  432   77  130
  768  647  123 1976]
[71]
[566  74  75  74  78]
[118 760 319 303]
[385 291 750 302  64]
[ 102  107 1092  251   91   92  234]
[1194  179    4  771]
[ 946   18 2371]
[451 325  56 256 257]
[381  88]
[  2   3 130  95]
[ 97  98  74  98  79  77 146  8

[932 469 130   9 317]
[141]
[274 727]
[ 24  49 885 886]
[ 137  315 2286  727   30  120  384 1210  479  109 2142]
[ 85   9   8 131 433   8   9 498 130   9 499]
[ 95 194 189 190 195 193 195  77  97 281 192 361]
[527 649 808]
[286 206]
[497 545  56 474]
[385  70]
[1134  694   39  414]
[ 502 2004]
[ 676   33  155 1215]
[141]
[752]
[ 667 1164  622 1102]
[367 368 369 370]
[1828 1473  820    5]
[ 73  72 484]
[1001 1584]
[1876 1307   43]
[1087   54  380]
[210 377]
[630 601]
[93]
[ 85 144]
[217 166  35  36 941 486 612 916]
[376 383  70 577]
[146  81  79  79]
[ 74 484 350]
[ 80 219  73  74  78  80 219 173 219  77  95 219 220  98 219  81  79  77
 484  79 350  72  74  77  95  96 280]
[173  72  81  79  77  73  76 350  81  74  78  98]
[1684   54  815]
[455 482 921 439 291  85  42  56 256 257   9 131   8  85 150 128 130 258
 129  85 258 144 258]
[ 43 792  43 644]
[81]
[ 64 177 316 120 632 783 316 241 277 234 286]
[  91   92 1066  262  503  431 1007  709  498 1007  258  258  151  199]
[711   8   9 129

[ 560  159  185 1179 1180 1181]
[277  43]
[ 206 1330]
[493 484 386 130   8 128 129]
[176 177 111 453]
[1913  396  619  275  276 1797  634]
[ 74 196 193 195 190 475 361]
[1133  773 1123  910 1388  682  714]
[461  47 477 538  99 365]
[75]
[97 75 74 81]
[2059  679  853  853]
[ 185 1080 1793 1794]
[85]
[406 407]
[ 68 239]
[8 9 4]
[875 875 585 445]
[ 493  493 2412  516  601  207]
[101 216  93 354 109  70 167 168 453]
[ 553 1308   28  908 2413 1280 1294  327 2414 2413]
[389]
[ 80 219  73  74  78]
[1849 1387 2316 1459  207]
[ 720 1534  439  291]
[219 190 189 281 190  75 475 476]
[146  97  95]
[488 690]
[ 75 219 220 220]
[2294  649]
[184 240 321 168]
[477 602 828]
[1042  451 1040  576  482  921]
[   0 1834  443 1644   60  484   72  484 1353]
[ 522 2415   42  279  240]
[1531 1516 2416  662  663  321  186    2  903]
[131]
[409 381 962 229]
[170 171 172]
[1445 1837]
[488 489  99]
[137 315]
[61]
[ 319 1995  482  200 1059 1014  556  197  231  316  163  499  199  186
 1206  316  316   64  596   39  

[ 39 811 509 822]
[357  96  78 357  74 230  27]
[78]
[ 702 1025]
[  24  808 1434]
[   0 2281 2282]
[131  85 129  85  85]
[756 401 771]
[ 95 281 317 317 281 190  77 173 281 193 193 189 361 193]
[ 102   93  354  913  128    9  799   77  179  913 1602   77  838  512
  319  874]
[902 383 495 496]
[643 283]
[128  85   8   8  86  86 129 129]
[ 73 475 549 549 476 711 189 196 188 194 282 475 476]
[1909    5  583  421]
[  82  664 2445    9 2445  663  262]
[ 85   9   8 128 150   9   8 150   8 130  77   8  86 447 130 129]
[1749 1754  210  377]
[1265   39  159 1015]
[241  38 272 893  36 363 877 387]
[493 484 219  85 131 130 258]
[1054 1675 2446 1207]
[ 921 1895  210]
[1425   64 2447]
[131]
[ 101  216  714  204 1147 1663   38  215]
[83 84]
[ 56 916 290]
[ 300 1831  258  379]
[ 36 291]
[1533   33  343  386 1609 1855  279]
[ 550 1014   56 1095  776  366 1041]
[427 338]
[484]
[ 146  475  361  475  190 1060]
[195 361 147]
[86  9  9 77 86  8  9]
[ 24 736 206 896 207  91  92 234 316]
[91 92]
[1355   40  

[ 214  512 1107  540]
[252 502 463 464 106]
[ 439  311 2471  583  129  129  115  116  239  240]
[1090  482  279]
[241]
[181 302 277 634]
[808  55]
[  41 2202  239]
[81]
[ 638  245 1825 1592  436   64   65   66   67]
[752]
[411  79  77  98  96  95 130 128]
[  50  376  278 1061]
[ 875 1535  989  969  141]
[209 123 903]
[144 357]
[75 72 95 95]
[345 421  70 577]
[652 330 353]
[ 822 1730   99  337]
[1331  134  397  608]
[330 330  66  57]
[609 477 602 828 300  25]
[1107 1063 1108]
[197 278 327]
[ 468  234  637 2064]
[176 177]
[1545 1433 1386  353  537   68  239]
[641  52  53]
[ 769 1433  562]
[1481   22]
[56]
[756  11 723 726]
[  96   81   74  146   96   78  386  515 1354]
[323 663]
[208 684]
[  9 130]
[ 179 1558  306   25]
[ 173  475 1060  195]
[35 36 37 38]
[ 626 1108    7 1054]
[86]
[107 108  49 239  66  67]
[  8 131 131  85 129 129   8 129 129 144 144]
[ 98  74  72 357  74  78 146  77 220  72 173  79]
[1315 1371   56  474 1331   56   57]
[71 73 74 78]
[  39 1741  119  137]
[ 778 1434 124

[ 174  175 1678  596]
[382]
[ 56 256 257 130  85 131 130   8   8   9]
[190 281 717 189 475]
[567 220  95  85 130 129 128]
[461  47 397 794]
[711 475 190 717]
[319 119]
[  88 1085  376  177]
[ 969 1427  319  303]
[  8   8 498]
[95 95]
[2490]
[876 278]
[2182  529  829  669  295]
[  70   77  640  257  382  773 2491  412  550  511 1427  489 2492  790
  168  295  638  611 2493]
[895 144 146]
[1410]
[ 166  844 1904 1876]
[2494 1297  349  637 1027  334 1131 1344]
[1014  639]
[1951 1465  609  477   66   54]
[ 56 256 257   8 130 131 258 129 258 131 144 129 129 130]
[ 107  108  499 2495]
[ 130 1162]
[2496   21  230 1112   24   25]
[ 54  49 546 239 556]
[1112  412  330  378  609  295  736]
[1979  342 1284  330]
[108 548 921 208 754]
[  99  643 1256  580  545]
[105]
[1116  295]
[379 166]
[231 168 456 457]
[  2   3 357  98 351]
[146  96 220 350  79  78  77 350  72  97  98  81  72  95  98]
[144 258   9 129]
[1107 1063 1108  684  488]
[249 278 453]
[323 535  35  36 144 142 576 690]
[ 491  914  284  6

[461 954 516 748]
[131   9   9 151  86 855]
[ 97 281 192 188 194  77 146 475 188 195 293 484 475 189 190  77 146 475
 188 195]
[  5 336 288 177 227 690]
[   8  131  130    9  129    8  258  131  130  129  258   60 2522  118
  213   63]
[ 623 2415   42]
[1134  694   39  414]
[1966  155]
[1017  692 2523]
[484 189 282 195 475]
[ 56 256 257   8 130 131 258 129 258 131 144 129 129 130]
[144 146]
[ 118  445  968  335 1023   30]
[822]
[ 427  875 1930]
[ 70 640]
[ 720  185  674 1407  386  199  712]
[ 85 146]
[79 78]
[ 756  120 1407 1816 2362  496  133    8    9    9  152]
[241 633  56]
[484 189 282 195 475]
[ 80  72 220  72]
[ 11  62 155  42]
[ 869 1326  179  512  257  450  869]
[1407 1605    0  216  101]
[141]
[ 79 391  72  98]
[611]
[484 189 187 711 361 192]
[ 808  378  507 1197]
[1510 1095 1510 1399 1136  338  679  991  658  775  320]
[ 808  444  485 2119 1592 1277  575  202]
[ 307  642  135 1007]
[2188  134 1156]
[711 219 220 220  66  28]
[477 928 453]
[1920  287  137  153  960   70   40  

[  44 2015 1242]
[439 157 972 643 577]
[ 13 968 105 276 870]
[518 559]
[ 80  96  81 220 350  77  95  72  98  76]
[1346  241   42  711    8  173]
[658 439 291]
[ 230  771 2205]
[1815  231  741  144  173]
[2538 2142  316]
[267 268 269]
[382]
[ 97  73  96  95 357]
[ 80 195 361 359 281 317 195]
[ 516 1669]
[2539 2540  393]
[ 40 204]
[  24   49  451  502   77  130  146   77  272 1481   86  447    8  129]
[144   9   9 128 128 128  85 144 128 130]
[75 73 76 98 96]
[1830]
[350 350 566  72  75   8  86 128 144]
[718]
[1012  493 2154 2154  562]
[80 71]
[510 183 379 482  91]
[ 81 195 193 188 196 281 281 317 193]
[339 343]
[1506  642   39  414  251  739  740]
[ 137  618 1493  859  800 1662  766 1161  346  916  766  768]
[277 279]
[ 160  346  137 1258   64 1302  573]
[ 85 128  86   9 258 258   9 130]
[1293 1474]
[  8 130  85   9  86   8 131 128  86  86 128]
[711 192 193 189 190 195 193 193  77 194 281 192 196 193]
[350  79 220  72  95  74  95  72  79  97]
[ 24  49 623   0]
[141]
[  99  649 2541]
[8]

[ 75  81  79 150  97  79  98]
[ 102  125  413 2563 2227 1364]
[75]
[1460  151 2564 2565 2566]
[130   8  85]
[1070 1070 1070  280  359  281  281  194  281  281  280  359  359]
[ 738 1253 2567]
[351  79  81  96]
[2568 1907   24]
[ 96  75  98  72  95  74 220]
[ 74  80  74  81 350  97]
[1265  168]
[ 471 1152]
[ 56 256 257  85 128 128   8   8   8   8   8]
[128   9]
[ 401  720  108 1426]
[317 281 192 188 475 189]
[181 182 714 204 111 482 345]
[ 85   8 447   9   8]
[146  81  79]
[  36  184  414   38 1077 1197]
[1589]
[311 121 214  49 315  99 649]
[79]
[1014  185  263  246  608  916]
[  11 1002 1003  644]
[2294 1821  386 1533  812]
[822]
[330  33 723]
[ 85  86 128]
[21 58]
[ 813  353 1545 1911]
[1054]
[325 379]
[130   9 215]
[461  47 714]
[919 450 562 729 730]
[96]
[  8 130 144 129 128   9 130 128  85  86  86]
[475 361 361  77 282 475 476  77 282 189 190 189 190 191]
[184  38 343]
[ 397   25 1133 1895   24   49  389]
[484 189 282 195 475]
[365 166 444]
[ 73 219  74  71  73  96  78 146  77 219 

[373 301 204 248 161 375  21 378]
[2217  518  354   91   92  234]
[  2   3 409   5 240]
[101 216   4 303]
[ 74  98  73 220  79  98  72  95  77  80  96  81 357  97]
[ 369  756  253 2581]
[756 647  56 690 429 272]
[184 709  40 204]
[ 273  213  647 1121]
[538  18 612 538]
[497 365  15 316]
[2128 1065  452   60  411  412   63]
[1663 1670 1390  607]
[401 110 153]
[1281]
[345 104]
[  8 258  86 258]
[188 194 196 281 192 191 194]
[ 8 85  9]
[1655 1656 1637  106]
[123 470 257   8 130   8  85 131   8   8 129  86  86 128]
[ 367  368  369  370  257  321  116   39 1255   64  177  320  315  321
  116   66   67]
[1131 1344]
[ 717  189  190  282  361  195   77  549  475  549  195  196 1070  194
  189  188  195]
[736]
[ 827 1591  345  444  714  278 1215  185 1359  145]
[ 86 129  86   8  86 129  86   8]
[ 645   14  295  560   14  467  515   35  609  295 1212  166  105  276
  103]
[ 85 146]
[1375]
[ 75  81  96  97  72 220 219]
[ 275  168  290  552 1290  952 1290  619 1334  872  310]
[85  9]
[ 8 85]
[121 

[121 924]
[1313    2    3]
[408 123 290 105 276]
[ 373  301 1017  749  345  168  575  202   64   65   66   67]
[ 27  87 472 207]
[  27  433  563 1116  218  157  311]
[553 168 505 865]
[367 368 358 378]
[ 664 1415]
[2148 1745  470  519]
[ 184 1014 1247  444   18  261  372]
[ 101  216  458  580  383  275 2017   64   65   66   67]
[ 93 354 461  47 714  54  49 185 642 467  41  42]
[141 529 141]
[129]
[ 790   30  290 1502   39]
[ 78  96 280 130 128   8  85 144 130]
[79]
[ 36 507 988]
[173   8 131   9]
[484 189 282 195 475]
[  92 1014 1081  382]
[200 201 165 218]
[518 559]
[536 253  56 256   8   8 258]
[1854  727  316]
[ 859  142  498  168  685  396  365  395  401  532  347  619   30  627
  365 1258  347 1185   30   83]
[843 593 269 158]
[ 97  74 220  79]
[319 273]
[838 528 839 182]
[275 482]
[ 415  203  714 1147 1663  240]
[ 96  95  98 808 912 714]
[   0  353  155 1690   77  569  166  155  207]
[ 813 2297 1571]
[496 488]
[ 319 1509 1852  709]
[  39  805  468  731 2599 1817]
[1167   99  376 

[330 431 144 150 131 498]
[ 86 129 128   8]
[ 667 1164 1302  573]
[1302 1238  649]
[ 101  216  204  111  808   56  686 1058 1301   64   65   66   67]
[ 272 1481  257    8  130  257    9    9  150    8  129  257    9    9]
[ 24  14 720 467]
[128   9 484   8  85   9 484]
[ 72  78 173  72  78  72  98 219  97]
[ 86  86 144  86 131 986]
[95 81]
[843 634]
[ 678 1016 1677  241 1125 1162  255  253  106]
[ 97  74 484  97 219  78 146]
[330 166]
[711]
[208 512 167 168]
[1436 1124   56  256  257   86  129  131   85  128    8  131  128]
[711  96  78 350  77  74]
[95 73 72 78 74 75 96 97 98]
[1506  642   39  414  240  739  740]
[549 196 281 282 192 359 195 282  77 722 476]
[81 79 95]
[484]
[120  18]
[8 9]
[220  72 351  79  77 173  96  81  77  78  96  80]
[1649  883  387 1459]
[711   8   9   9 130 258]
[357  72  78 146  73  96 484  79]
[428 644 275   5]
[ 184    2    3  386  126  184 1663]
[605  74 566 351 129 258   9]
[ 495   35  718 1425   36  482  382]
[166 953  58 217 217 238 292 292 778 489  41 

[181 182 518 559]
[1815  231  741  357   98  351 1017  215   42]
[1948  298]
[ 692  608  732  213   24   30   39  891  740 1967 2228]
[   5  691  855 1019]
[1262  382  442]
[177 320 197 839]
[ 79 484 350  74 220  79  77  79 484  72  78  79  78  95  79]
[ 62 216 111 421]
[  9 258 498   8 129 499]
[24 49 56 88]
[1389    8    9    9  151]
[146  81  79  79]
[  8   8 129]
[ 196  189  190  717  193 1012  298  330]
[2629 1081 1082  543]
[ 938 1500]
[  8   9 151 130 996]
[ 317  281  196  195  447 1353]
[144  86   9 151 913 320]
[ 111  686 1937 1794   30   50   51 1987 1391   30  379  327  164 1247
 1828  166  398  310]
[ 283  589 2570 2630]
[144]
[74]
[ 985  568  783  537  822 1730]
[ 714 1672  410  439]
[144 146]
[241]
[184 690 230 424 248]
[  65  843  844   30  321 2211  425  932   30 1147 1663 2631  365   30
   64  767  365  723]
[2632  815 2357  525]
[720 185 185 742]
[ 85   9 131 191 391   8  85]
[ 111 1319  106 1816]
[1194  179 2243  241]
[350 295 257]
[210 377]
[1436  278   56  256  257

[1134  694]
[516 875 593]
[ 176  177  938 1628]
[562 207]
[   3 2083]
[ 714  455  531  507  121  460  936 1035 1096  732]
[220  72 150  78  72  78 146]
[ 346 1305  104  345  348  496  133]
[195 361 147]
[1186  365  303 2078  316]
[81]
[1081  165]
[1020  964  181  324  439  291]
[ 353  356  386 2647  108  386   40  487  386  108  548]
[106 240]
[ 300 1831   85  379]
[  27  168 1648 2036]
[372 515]
[  8 131   9 241 320]
[962 229]
[1013  345  725]
[ 730 1219  808 1133   34]
[  85    9    8  128   77   78  195 1070   77  711  475  361  475  190
  359  195   77   74  188  194  361  195  188  189  359   77   97  194
  281  195   77   72  190  359]
[155  33 421]
[121 916 450]
[456 457]
[ 216   38   62 2560]
[ 401  660   90   41 1211  240]
[ 319 1229  380]
[ 347 1843  114   22]
[ 98 484]
[  8   8 447 144   9 835 835   8  85 447  85   9]
[349 230 957 168]
[ 86 129 258  85 130 144 131 128]
[  85 1054  241  530  241]
[1040  576]
[ 724 1130   99  337  714   91   92  234  316]
[454  25 806  56]
[ 3

[195 476 191 195 476]
[ 718  250  315  678   24   49  389 1162  208  839  414   43  227]
[ 619   30  137  315  953  779  780  468  134  858  123  794  619   30
  750  384 1294  841  111 1649]
[101 216 204 609 295 247 248]
[ 24  49 623   0]
[174 371]
[ 54 382]
[  8 258 129 130]
[131 258 129 130]
[ 323 2658]
[  8 258 280   9   9]
[129  95]
[ 78 146]
[350 476 190 475 317 189 359  77 189 190 193 188 189 188 192 188 195]
[1471]
[ 98  72 484  79]
[1089]
[ 92 469 311 424 445]
[ 272 1481   86  447   85  130]
[157 121]
[2659  155  518]
[1639  342  533  792]
[  40  487  502  262  638 1570]
[2392]
[ 96 147 147 189 359 195  77 193 549 475 359 195  77 188 281 192 196 189
 193 188 193  77 193 188 281 549]
[ 182  741 2660]
[ 98  96  78 146  77 220  72]
[722 475 722 476 194 281 281 282]
[ 163  164 1292  690  788  186]
[359 281 317]
[ 451  325  379  257 2661  843 1516]
[124 815 816]
[1751   92   93 1658]
[1858   57  321  116]
[189 190 190 189 193 147 196 195 195]
[1503  107   66  378  574  377  205]
[1

[525]
[ 137 1605  916]
[ 529 1051]
[ 842 1693  206  609]
[1715 1716  279]
[97 73 79 79 78]
[ 495 1034]
[ 36 291 130 855 199]
[ 75  96  97  98  74 220  77  97  74 351  72  78 146  97  77 711  74  78
 357  77  96 173  77  95  73  72  78  74]
[  39  805  573 1374]
[210  56]
[ 428  429 2678   88]
[219  81 219  77 357  74 350  72]
[425 644 754 303  30  39 326 241 617 833 316]
[ 35  36 502 421]
[258 215 337 754]
[ 15 210]
[ 86 129 131 128  86   8   8   9]
[ 95 281 317 317 281 190  77 173 281 193 193 189 361 193]
[1170 2637 1918]
[1446  265  514    8  151 2171  436]
[130   8 150   8]
[ 24  49 623   0]
[ 105  276  463 1698   56  256]
[694]
[ 576 1108 1318 1988   82  166 1679   95  366]
[1416 1906  121  250]
[ 101  275 1108 2679]
[1213 1460 1042 1043]
[ 914 1385 2680]
[2310  155]
[220  79  77  97  98  81  79  79  98]
[ 208 1967 2681 2301  365   35   36 1480]
[128]
[496]
[2682 1622   64  550]
[ 737  326   56 1136]
[ 86 131 131 128 128 130 128   9]
[ 97  73  72  81  79  78  77 391  72 220 219]
[ 

[ 832 2101  870]
[ 56 256  85 128 128 128 128 129 130]
[711 150   9   9  86]
[ 101  216  827  142  239  240  512 1134 1463  111  754  200   92   93
  354  409  992]
[2694 1913  468 2695]
[195 475 193 476 361 475 717 195]
[ 98 195 282 282 476  77 711 195 475 196]
[159 160 109 161]
[ 81  79  98  74  72 220  77  75  81  72  95  79]
[   9  827 1007]
[ 109  919 1613  311  638  142  939]
[ 396  814  289  814  186  290 1502]
[24 49 56 88]
[2696 2697]
[181 182 714 204]
[2015 1242  516]
[  64  628  256  315 1258 2698   30  137  620  621  316  316]
[1247 1642]
[ 728  396 1332  944  657  658 1035 1096]
[219  75 362 317 475 196 717 195 188]
[ 657 2075  111 1319  106 1816]
[317]
[ 413  141 1256   17  386  487 1695 2699]
[  11 1025 1015  213  961]
[317 281 476 475]
[ 79 391  72  98]
[91 92 93 94]
[  64  470 1602   28   84]
[2700]
[ 95 194 189 190 475  77 484 281 722 189 361 195]
[ 102 1104  913 1104]
[146 189  96  78  79  79   0   1]
[1928  990  850 2123  378]
[ 36 507 988]
[190 475 188 281]
[1453  

[  21  907    7 1096   52 1551]
[ 70 640 257  24  14 467   8 131 150 144 215]
[1093  671 1350]
[1592]
[ 78  79  80  77  74  81  81  72 351  74 220]
[359 194 189 359 281 190 476]
[359 475 147 195]
[ 248 1671 1986  330  378  239]
[129 131   9 484 520   8  85 484  85 131 484 128   9 484   8  85   9 484]
[662 663  11 209 266 665]
[  74    8  280  711    8  280  711  130  280  711  144 1883]
[  8 129   9 293  86  86  74]
[109]
[85 86 86 86]
[662 663]
[284 642  64 137]
[184]
[251 378 529 105 276  24  25]
[  8 215]
[1473 2105]
[711  73 131]
[593 401 261]
[ 203   93 2031  203  262    5]
[1613  353   84  155]
[ 86 129  85 258  85  86  86 128]
[382]
[130 317]
[ 123  470 1744  726]
[596  22 389 661]
[ 101  216  756  251   24   25 1081  490  105  276  103]
[209 290]
[1112 1375]
[203  93   2   3 240]
[1170]
[ 101  216   70  111  550   62 1737  875   64   65   66   67]
[2247  420]
[549 192 722 361 189 359  77 188 281 189 361 195 188]
[111]
[981 412 533 792]
[ 71  72 146 219  72  73  96  98  79 220]


[ 56 256]
[ 495  532 2000 1375]
[1170 1021  883 1757]
[432 936 428 429 257  86 128   8 129  86  86  86]
[281 317 195]
[240 319 960]
[444 975 230]
[428 429]
[130  85   9   8 128   8 130]
[1115   34]
[ 700  104 1164  641]
[ 792 2039  913  401  458  913  319  239  913  902  752  386  386  386]
[ 11 284]
[1463  948  530  257   85  128  131  129  128  129]
[359 195]
[379 596 118 213]
[ 522 2415   42  279  240]
[1300  433  321 1058]
[ 50 376 585 445 342 488  52  53]
[ 725   41  611  638  503  240  545 1407  274  727]
[383 176  66 679 239 240 482 302]
[ 667 1164 1208  947]
[ 108  548  397 1343  754  553 1312  841 1106]
[ 855  404  110  433 1797   57  319  263 1781]
[184 884 216]
[ 535 1125  535 1677]
[  8  85 498  85 144 499]
[ 85 151]
[605  74 447 129 130 130  97 130]
[144 280 131]
[484 189 282 195 475]
[1694 1694 1105]
[ 98  96  75  77 173  79  79 220  72  78 146]
[ 125  139  105  276 1325 1439 1280  680  139  105  276  384  425  315
  595   83  105  276 1325 1439]
[ 155 1215]
[401 920 921 

[ 85   9   8 128]
[1059  234    7  273]
[117]
[548 157 606 207]
[1475  123 1133  345  181  182  714]
[ 323  536 1707]
[482 247]
[1671   20  433]
[73]
[ 317  281 1070 2048 1474]
[837 731 414]
[ 98  96  72 220  79]
[249 156]
[ 472   31 1247 1460]
[ 379  166 1006  618   64  134]
[ 720  185 1241  531  515]
[ 409 1075  266  665]
[ 343  120 2743  353 2744   28   84]
[492]
[ 250  250 2149  338]
[1115 1625  227   43   24   49  389  409  742  916  690]
[ 487  914 1284 1285  601  562]
[ 536 1453 2745  516]
[85  8]
[ 646  268 1770  103]
[167 168  24]
[ 443  444 1027 1204]
[95 74 72]
[131 173]
[680 496]
[103 106 257 144  85  85 131   9   8  85 144]
[ 550 1889]
[  80  192  194  475  190   77   76  195 1060  189   77  220  281  193
  190  190  195  188  189  359   77   97  281  196 2088  281  196  476
   77   73  281  193  549  189  188  475  361]
[219 484  74  97 357]
[980 815 290 103 414 103  38]
[399 109 231]
[  99  100  569 1764  337  138   33  827  333]
[173 350]
[114   5 266 665]
[ 319   25 10

[2312 2312  334]
[ 74 317 195 196 189 475]
[765 692 169]
[57]
[ 97 219  78 173 220  96  80  79  81]
[ 56 256 257  86  85  86 258  86  86  86]
[2294  649    8  131    8  362  362  362  362   86  129  128  128]
[313 330 406 655]
[ 720  179  783  425 2031  203  553  482]
[ 353  976  623  301  687 1146  377]
[1964 1965  330  378    8  144 1883]
[2078  316]
[204  42 260  30 331 260 330 378  40  30 144 142]
[241  42 275 770 174 371]
[283 975 230]
[401 550 969 515 525 207]
[ 95  81  96  95  96 350  72 220  79]
[ 137 1331  181  182  397  608]
[252 458]
[130  85 131 130   8   8   9]
[414]
[111 217]
[184 499]
[  8 258   2   8 258 503]
[ 189  188 1991  193]
[1216  231  741  461   47   85  173]
[701  98 220]
[217]
[ 718 2118 1300 1658  383  507  502]
[115 939 153 396 477 347]
[1171  166]
[1268  212]
[157 206 609]
[1155 2105  609  477  602  828  300   25  496  133  987]
[1481  278  257    8    8  257    9    9  150    8   85  257  144    9]
[ 638 1570  980   93]
[ 184 1749  210  477]
[482 377 378]


[980  93  99 482]
[ 847  458  153  363  166 1185   33  252]
[1145  790  295  296]
[391 128]
[317  98  79]
[701 701 447]
[174 175]
[ 241  103  512    7 1672  495 1027]
[ 531  148 1623  786  279]
[240   4 418 419]
[2712   36 1683  209 1355  961  679  572  776  702  424  212 1312  679
  792 1190 1296  450]
[  72   77 1070  475  190  188   77  194  475  513  195   77  189  190
   77   97   96  146   74  220]
[ 421 1169  790  821 1059]
[ 585 1096  739  740]
[1012  298   99]
[ 184  313   43 1121   77  249  503  249 1602  377 1122]
[711 196 189 191 194 188  77  75 281 188]
[ 323  536 1707]
[ 927 1076  754]
[286  90 468  11 808]
[ 97  74  78  76 219  74  78 701  72  74  96  77 711  81  74  78  95  73]
[ 125  429  274 1377]
[101 216 720 107]
[ 689 1923  137  207  404]
[382]
[130]
[  8 173]
[ 151 1666]
[  73   79  220  220   96 1420]
[85]
[  4 691 577   5]
[129 144 280   9 799]
[846  14]
[1134  694]
[131 130  85 507]
[209 917]
[1655 1656 1637  106]
[2223  123]
[83 84]
[56]
[339 343 562 207 118 7

[1153 1014]
[ 54 444 185 642 467]
[ 265 1755  277  278   85   85]
[484  74  78]
[ 74 196 195 475]
[ 869 1782  233   85]
[454   6 386  49 455 330 378]
[ 24 114 181 324]
[  9 144 128 129 129]
[550  62 997 166 516]
[ 408    9  241 1012  433  241  498]
[1147 1663  240]
[121 753  50  51]
[ 869 1782  233    8]
[566  96 711]
[ 272 1481   86  447  144  131]
[ 616 2777  913  995  428]
[2538  626  240]
[ 612  916 1137   65  130  109]
[  38 1631  114  238]
[389]
[219  78  72]
[371 131 530  85]
[1070  475  188  193  281  190  193]
[ 74 359 359 195 193 193 281 196 189 195 193]
[  85  144    9  317   85 2727  754  534  613  634  111 1463]
[ 80 192 194 475 190  77  79 475 193 188  77 220 475 717 195]
[97]
[247 789]
[ 515 1200 1616  337  275  240]
[ 442 1134]
[131  85]
[ 667 1164 1208 1489]
[ 86 131 151 913 320]
[2370  975 1034 1106  210  536]
[11]
[202 203 376  35]
[276]
[ 24  58  58 213]
[1291  747  450]
[ 101 1877]
[1042 1043  884  378 1044]
[ 85   9   9 131]
[643]
[  60  641  608  467  251  295   

[1200 1252   57  181]
[1549 1120  634  410  338  340]
[1223  918   56  256  257    8  130  129   85    9  130   86   85  128
  128   86]
[ 41  40 123 790]
[1670  691]
[ 678  283 1162]
[  8 131 258  86  85 129 129 129 129 129  86]
[2116  586 1173 1116  295]
[  24 1717 2797  382]
[919 517 321 186]
[  70  106  257  275 1196  204 2614  714 1095  237  238]
[1617  389  562  279  207]
[  83 1156  315   30 2476  137   30  628]
[495  35 251 378]
[  8   9 131 317 361]
[290 699 462 404]
[24 49 56 88]
[141]
[ 24  49  93 354]
[  39  805 1475  914 1539  273]
[  43  792 1779  222]
[1054  530]
[1392  412  204  427 1759  494   66  378   23  213  750]
[319 487 313]
[484 195 196 196 476  77  95 194 196 189 193 188 317 475 193]
[ 674 1115]
[ 672 1916 2798]
[1351 2016  643]
[ 137  241 1758  468  862  135  137  859  142  433  954]
[605  74  77 128 351  81   9  86]
[2063  689   19]
[ 515  593 2799]
[483 433]
[1532  482  686  336]
[379 273 737 442]
[484 189 282 195 475]
[167 168  24]
[ 528  489 1256  643]
[10

[  67  140   93   30 2291  319 2812   30 1419  379  179 1281  396 2098
 1300  404]
[497 680 496]
[  8   9   9 484]
[2813  316]
[ 321  217 2078]
[44 28]
[732 732 197 435 898 451 502 144 146]
[458 642 369 370]
[1515 1516 1517]
[ 107  102 1227  379  246  886  812  241 1017  614  763  433  408  498
 1069 1551]
[1036 1037  379  257 1321  676  182]
[493 386 484]
[303 330 166]
[ 409 1846]
[711   8   9 129]
[206 353 240]
[2814  619  404]
[188 196 475 190 193  77 359 475 196 193]
[203 560   2   3]
[453]
[1132   14  875  275  168  467]
[  8 131  86]
[192 190 189 359 281 317]
[ 376 1676]
[258 215]
[ 49 482  56 274]
[220  74  78  97  73  72  76 219]
[617 833 878 215]
[ 79 391  72  98]
[101 216 502]
[367 368 369 370]
[ 97  73  74  77 391 219  74  78  77  71  74  96  77 391  72  78 146]
[ 969 1427]
[199]
[ 99 315]
[2573 1343  266  665]
[ 536 1453  827  822  316]
[1625]
[502]
[283 231  34 396 289]
[687 506  56 916]
[ 411 2217  406  407 1510 1095]
[ 105  276  169   60 1386  789   63]
[ 107  108 2243  

[737 198 197 231]
[ 143  404    1  163  891  286  576 1108  143]
[1625  522]
[ 438  390  603 1517]
[ 204  821  206  442 2522 1359]
[ 102   99  471 1669  313  525]
[ 692 1970 1834  146  189  190  717  191  281]
[ 18 590 576]
[1602  245  239  744]
[144 131 317  85 409]
[822]
[ 601 1529  178    0   60   75  484 1353]
[456 457 609 477]
[ 73 475 190 191 194 475 189  77 220 281 190 191  77 350 189 193 188 475
 190 359 195  77 711 192 193  77  97 188 475 188 189 281 190]
[ 142  379 1042 1233  257]
[ 95 194 195 195  77  95  96 220 220  79  95  98  72  96  78]
[1112  412  111]
[666 667 425 311]
[ 80 192 194 475 190  77  71 281 281]
[664]
[439 440]
[ 885 1046  123  470  692  608]
[72 95 96 78]
[765 568]
[653 654 792 516]
[109 753 686  23 421]
[1777 1777  208 1175  997 1141  239  240]
[252 458 968]
[ 307 1072]
[184 749 493 380]
[9 8]
[ 80 195  77 717 195 195 549  77  98 194 195  77  79 190 513 189 196 281
 190 317 195 190 188  77  72 190 513 189 188 189 190 191]
[ 616  148 2830]
[ 487   88  625 1

[350 281 190 191  77  78 189 317  77  95 194 189 190 191  77  81 195 193
 188 475 192 196 475 190 188]
[423 972 695 516]
[ 487  313 2845  245]
[220 219  95 357]
[1948 1607   41 1051   45]
[409   5]
[ 142  379 1015  213]
[98 79 78 78 72 97]
[ 274  640  257 1070 1070 1070  280  194  281  317  195  189  190  190
  193  280  359  281  317]
[ 839 1399  892 1399]
[137 315 765 568]
[ 21 907 109  70]
[ 7 24 25]
[1472 2713  499 1049  110]
[2063   57  315  349  230  468  894   21  310]
[498]
[219  78  72]
[1292 1293  123  470]
[ 78  96  78 146 173 219  77  97  75  81  72  78 146]
[1090  250  470   56]
[ 709  709   37 1319]
[1749  482   99  921]
[711 281 513 475  77  98 195 196 196 475 359 195]
[125 345]
[351 189 282 195 281  77  81 281 281 317]
[1445  975 1256]
[286 374  58]
[373 301 204 379 246 886 812 616 423 176 596 732]
[1144  421  182]
[  8 130 151]
[1216  429  325  963]
[  86  379  700 1220  765  663   52 1551  257]
[ 80 195 282 190 195 193 282 475 476]
[ 37 699 495  35]
[   4 1879 1027  3

[1107 1063 1108   85  131    9 2027  132]
[484  74  78 484  74  78]
[105 276 428 429 257 144   9   9 150   9  85 129 150 129 128]
[ 381   88   38 2191]
[181 182]
[644]
[1974  765 1320]
[   8    9   86  841  168  602  315  241 1033  333 2136]
[1717  390 1256]
[484]
[615 210]
[  3  99 768 231 217]
[462  64 919 517]
[2850  521 2850 2588]
[ 56 256 913 737 284 257   9  85 129 150  86 129]
[1625  218  718]
[ 24  49 692 608]
[313 387 111  45 386 386 386 386 386 386 128 151 436  85 142]
[128   9 128 258   8  86  86]
[  24 1133  110  153  204  821  736  737  870]
[743 646  44 155 744]
[1602   24  112  776  127   30   35   36  844   26  756   30  396  477
  636 1280 2851]
[146  79 484 488 489  99]
[ 263  383 1497  955  240]
[ 229  761  166  612  295 1074 1442 2142  917]
[210  56]
[ 134  627 1034 1334  872 1178]
[  8 131 128  86 131 357 146]
[1489 1490]
[128 131]
[ 484  195  188  195  196  193  722  281  190 1070  195]
[1336  231  123  790  207]
[350  79 220  72  95  72  96 219  97  77  75  81  9

[330  33 489]
[220  72 173  79]
[  93  354  111  421   41   50  429 1008  482   14  108  507  790  607]
[ 475  190  190 1070  475]
[1035  323]
[ 56 256]
[101 216  70 531]
[258  86 799]
[319 630 623  28 387]
[571 572]
[ 120 1296  512 1672  302]
[223 597 803 804]
[ 377 2199]
[241 903]
[1613   85  215]
[428 536 228 109]
[  27  229 1588   19]
[461  47 714]
[ 210 1024 1229    8    9  151 2678  550 1535   86  151]
[1001  111  382]
[ 319 1229  131  151]
[1216  120]
[328 329 962 229]
[ 85 258   9 131  86  86  86]
[ 550 1665  668  315  742  687 1150  179]
[662 663 289 290 291]
[1260  382  428  429  257    8  130   86   86    8  128  258    8   85
   86  128]
[ 214   49  737  326 1215  337]
[602 167]
[ 95  95  98 351 130]
[346 234]
[522 382 433 433]
[ 229 1297  439  440]
[1185  998  396  621  321  210 1793]
[ 661 2862  428  642  315 1231  460]
[ 900 2241 1986]
[2006 1040  182]
[100 420]
[ 307 1072  239]
[ 125   65 1081  165]
[916 690]
[1602  208   38  343]
[1028  908  646 1216]
[146 219  74  78]

[   2    3  184    5  822 1730]
[ 78  79  80  77  95  73  74  78  78  79 220]
[409 664  56 916 290 679 798  22]
[   0 2875 2876  707  290 2335  231  870]
[987  93 536 290 130   9 151  85 848]
[ 396  120 1213  765  273]
[1080  901 1960 1116]
[ 80 192 194 475 190  77  79 475 193 188  77 220 475 717 195]
[95 73]
[634 410]
[2877 1424  427]
[ 146  475 1060  475  190  358   14]
[  8   9   9 152 284 908 908 914]
[203  93 482 485]
[566 195 195 549]
[101 216 720 107]
[ 720  179  203 1711]
[461  47 714 439 291]
[ 213  596 1055  841]
[ 518 1784 2184   30  217  924   40  315 1049  448]
[ 808 2878   58   59 1592]
[2879  690 1473 2105]
[218 516 562]
[324 158]
[767   5 770  57]
[ 946 1902  759  749   37  750]
[ 93 354  49 455 439 291]
[ 181  213 1846 1923   30]
[  95 1124    8    9   42]
[444 512]
[ 85 128   9 128   9   9  86  86]
[123 403 255]
[2091  200]
[91 92 93 94]
[ 81 195 317 281 513 195 193  77  75 484  85 280 131]
[101  55 516]
[674 311 104 935]
[569  25]
[1265  168]
[ 74 711]
[  8 498]
[ 29

[ 111  123 1798]
[167 168   2 903]
[ 947  102 2286  148]
[ 36 607 463 464]
[49]
[2890 2051 1256]
[317 281 190 189 188 281 196 189 190 191  77 475 190 282]
[ 85 144 194]
[ 109  421 1689 1416]
[ 654  642  274 1131]
[97]
[174 217 169]
[ 241  503  594 1258 1677  479]
[ 181  320 2891  897]
[166 313 115 116 497 204]
[  8 144 258 258]
[439 440 841 174 371]
[220  72 173  79]
[2892  672 2523]
[146  81  79  79]
[  73  475  549  549  476   77   78  195 1070   77   76  195  475  196]
[1317 1281]
[ 234 1974  414  699]
[876 278]
[ 822 1730]
[605  74 386 484 484 258 144 258]
[218 157]
[  85  115 1081   97  566   95   30  468 2349   37  315   47  562   24
 2228  177]
[345 773 181 182 714 204]
[ 725   41  446   36   49  181  273  528  891  396  120 1296  916  181
  273]
[ 657  241  657   40  562  315  408   82  658  205 1789   30   17  137
  902   88]
[ 756  534 1588   19  572  776]
[ 86 129 129  86  77 128 128 128 128]
[ 290  679  798   22  290  679   56 1627  290  679]
[ 98 220]
[592 957 482]
[ 142  

[  85  215   56 1032  453]
[85 86  9]
[1112  412  111  421]
[  8 130  86 129   8  85   8 144]
[  97  717  189  189  190  191  764  146  196  475  193  193 1353]
[1409  679  972  482 1433  353]
[ 550 1014  507  749   37  750]
[ 66 262  56 256]
[643 901  24 278]
[ 73  79  98  74  78 146  77  75  72  79  81]
[ 93 354 109  70]
[608 886 596 276 105 276  24  25]
[111  68 380]
[701 219]
[130  85   9   8 128   8 130]
[614 241 507]
[ 687  672 2258  229]
[1858   57  321  116]
[  97  192  190  189  190  191   77  411 1020]
[8 8 8]
[281 190 195 280 130 258 432 936  24  25]
[85  8 86]
[2667  854]
[1116  987   42  593]
[ 80  96  80  77  95  74 173  79]
[ 323  535   35   36  379  379  124   77 1223  535  536 2049  573  111
  482]
[ 689 1333 1210  109]
[144   9   9 317]
[  99  343 1064 1350]
[249 545 546 239]
[1258   25 1258 1451]
[1017  741   56   57  255]
[ 630  279  989 1722  279  989 2900  279]
[1329   64  134  917 1522]
[367 518]
[8]
[95 74 97 72 96]
[653 977  24]
[  45  616  496  536 1453 1223  

[1485 1112  754  104  935]
[1425]
[128 151]
[219  97]
[1337  505  105  710  240]
[163 120 110 346 477 169]
[129]
[428 616 562]
[ 381  175 1012  493 1227 1294  204  679 1427  432  936  118  213   30
  490 1154  131    9    9    9  151  384   40  404  618  842  257]
[1549  533  792  295]
[616 377]
[241 217 435 477]
[838 528 839 182]
[1950  968 1065 1383]
[ 667 1164 1165 1111]
[1087 2116]
[ 184  808  451 1671  433  714]
[ 625 1327]
[  36  499  776  121 1382  385   58  643  901  993]
[2258]
[2625  199 2625  199]
[350  81  79  74 484]
[1227  114  238]
[321 905 111 261]
[536]
[633]
[  97  475  188  189  190 1991  193   77  549  189 1060 1060  475]
[130 484]
[1797 1516  208  634]
[  8 258 258 151]
[642 379 758]
[ 36 458 482 921]
[326 241 900 155]
[  24  808  379  246 1133  518   49  247  248  870]
[639 709  37  11 316]
[ 25 444]
[475]
[75 96 72 78 98]
[634 664 132 534]
[763 295]
[162]
[311 472 427]
[612 916   2 903 258 498  85  85 499 292 292   8   9 498 129 499]
[2909  390]
[ 157  121 1281  

[643 644 291]
[357 317 293 194  77 484  74 391  72 484 219 484]
[ 111 1319  213  165]
[ 56 256 257   8 130 130 144 258  86 130]
[ 241  142  170  171  172  334 1914  241  142  777]
[518 201 340 213]
[1515 1516 1517]
[  25 1381   25   64  444  968  120]
[2207]
[ 76  96 219  77  73  74 351  79]
[1408  148 1180 1459]
[217 166 468 251 378 462 414  37 693]
[ 425  311  290 1502  667 1164  699  462]
[1459]
[577   5]
[251 378  23 213 684 572]
[ 41 813 239]
[2319  619  404]
[  8 131]
[ 99 270]
[173  96  95 219  97]
[ 454   25 1049  210]
[357 475 549 549 475]
[ 662  663   93 1653   40  274]
[ 95 989  74  77  97 188 475 147 147  77  79 190 188 196 475 190 359 195]
[ 487 2925 1203]
[   4    5  790 1041  240]
[ 56 256]
[792 883 748]
[ 461   47  714  317  281  196  195  447 1353]
[ 465  390 1429 1256]
[ 95 194 195 190 147 195 190 191  77  81 281 475 282]
[2039  353]
[ 156  143 1454  898]
[537 215]
[1013  518]
[125 429  80  72 173  72 662 663  40 274]
[ 650  612 1295  742  118   77 1936  690  435  369

[ 241  330  241  976 2702  166  953]
[382]
[107 108 237 238]
[2933 1197]
[ 101  216   56  429  408 1041]
[ 79 391  95  79 220 220  79  78  98  77  97  98  79  74 357]
[396 126  17]
[ 131 1690]
[492  85  86]
[146  79  81 484  74  78  76  77  97  98  76 220  79  77  97  98  81  79
  79  98]
[249 275 274]
[504 604]
[1167   99 2611 1015]
[ 463 1698  379]
[ 80  73  81  95 711 711 475 190 717]
[ 95  73  72 220 350  81  79  78  97]
[623 624 265]
[  14  720  604  110 2834  111  427  338]
[1417  377 1760  390  690]
[ 85   9   8 128 184 433 298  92 184 829 863 283]
[2882   83  239  240]
[225 226 227  70]
[  2 886 618]
[  93 1821   58   59]
[497 204]
[1677  479  435  934  479  316]
[  8 131  86 129   8  86 131   9   8   8   8]
[ 679 1141  875  679 1141 1803  679 1141 1000  679]
[258]
[2749 1230  968]
[208 468 167 168]
[  53 1113  105  276  840]
[495 496 497 204]
[ 92 234]
[  9 129  85  86 150 130 130   8 129 130 129 129]
[822]
[1937]
[98 97 72]
[ 159 1515 1256   77  345]
[ 98  81  74 173 173  72 

[ 148 2707 1115]
[1554  423 2946  901  118  985]
[1134  694]
[  49   99   56 1136]
[ 875 1495]
[526  85  85 151]
[2947 1515  558   22]
[428 432  24]
[1951   54 1465  223]
[364]
[   8    9    9  152   65  572  577  121 2035  383  553 1834   64  470
 1412  291]
[101 216 197 231 503  34  58  59 165 830  64  65  66  67]
[ 526  131  144  280  131   77 1227  526    8    8]
[  9  85  86 150  85 128 128   8 131 131 128  86]
[144   9 913 320]
[ 210  495   30  384  263  538  365  315  346  439  111 1957  968]
[1877]
[  62 1140   24]
[98 74 96]
[75]
[ 799  379   66 1774]
[ 490 1154]
[  24   49 1147 1663]
[513 189 513 281]
[85  8]
[ 210  850  301 1122]
[ 720  185   52 1033]
[ 95 194 195 359 194 195 190 191  77  81 281 475 282]
[319]
[1112  342  353 1841  325  963]
[1392  412 1147 1663   99  611  503]
[86]
[422  62 111 421]
[246 602 507]
[1515 1516 1517]
[ 319   25 2948  758]
[ 85  85 447   9   9]
[707 290]
[739 740  56 256]
[ 80 192  73 475 190  77  79 475 193 188  77 220 475 717 195]
[711  74  72

[ 859 1616  561  451  363  559 1916  378  462 2061 1608  754]
[2474 1297]
[  8  86 447 130   9]
[ 623 1057  389  404  753  673   30  880 1385   18  433  315 1290  952
  321  186  518 2957   93  569 2958   30   49  690  396  120  397  499
  673  723   30]
[35 36 37 38]
[753  99]
[167 168  24]
[219 190 189 281 190  75 475 476]
[  70  531  408  215  429  527  482  494  103  350   37   38  469  608
  131    9    9 1216]
[  66  246  421   54  773 1058  227 1145 2959  618]
[128   9]
[ 93 354]
[1281  512  452  106]
[450 562  37 371]
[246 602 507 240]
[  12 1399  737 2369]
[1572 1455]
[ 180  181  182  404  183  184  185  404   66 1075  439  440]
[   8   86    9    9    9    9  317 2960]
[ 13 529 295]
[ 95  81 150 351]
[   0 1086  335]
[201  13]
[ 730  159  261  427 1213  482]
[324 158]
[ 24  49 495  35]
[566  97]
[74 79 79 79]
[324 158   5]
[ 981 1086  707 2017]
[ 687  231 1318]
[2154  376]
[ 85   9   8 131 433 131 498   8  85 499   8 258 447 130   9]
[ 241 1631  428 1919]
[ 64 106 401 768  64

[ 193 2088  361  281  513  195]
[409]
[2591 1102 1405  393]
[  39  805 1528  226]
[  41 1306  379  482]
[258 151]
[1389  109  741 1108 2679  512]
[111]
[2498  518]
[64 65 66 67]
[246 921]
[ 39  40  41  42  77 536 148 278 453]
[ 330  431 1012  498]
[1549  470  916  290]
[95 75 72 95]
[79]
[ 341  545 1576 1605]
[1252  305 1254 1215  340]
[1001  241  835 1001 1012]
[ 576  289  272  311 2097 1936  462   25 2662 1309]
[2190  197]
[ 689 1333  463  464  295  296]
[111 644 291]
[75]
[1493  121 1642  554  479  315   36  440 1462  137  858   30  286  286
   43  468]
[1425  412]
[  73  220   74  487 1363   33  482]
[  93 1161  269]
[439 440 174 691]
[345 444 350  72  76 295]
[   9    8   77 1312]
[ 583  272 1676  642]
[ 346 2635 1206 2605  901]
[220  96 146  96  97 219  78  77  73  96  98  79 220]
[351  72  75  77  73  96  98 220  72  78  79]
[  40  487  487 1487  337    5   64   65   66   67]
[1483 1484  990]
[  0 515 919 517]
[ 466  240   57   30 1255  231   57]
[321 168]
[ 95 194 189 190 475  

[ 986  408 1649 2984 1654]
[ 569 1764]
[1486  487 1487  537  338]
[ 79 350 219  95  74  98  72  96  78]
[319 217   8   9 280 131   9]
[146  81  79  79  78  79  81  76  77  95  74 173  79]
[1090  184  575]
[  8 131 129 129 131 129 258  85  86 144]
[  8   8   9 131   9]
[350  79 711]
[435 160 346 137 550 287 120 159  30 134]
[357  79  79  81]
[ 210  377 1239  337]
[  36  246  124  626 2985  316  316]
[1797  379 1231]
[ 95  96 173 173  79  79]
[  9  85 129 150 131 258 130   9  86   8 130 130]
[ 85 128  86]
[54 49]
[ 319   25 2948  758]
[382]
[657 241 657]
[ 448 1803  387]
[  8 131]
[  85  146  581 2986]
[  66 1075  439  440]
[1798  442  385]
[1120    7 1054  201 1786   18  337  262]
[ 98  96  78 146  77 220  72]
[ 40 302 109 181]
[350 128 191]
[ 395   88 1037  363  241  800  197  231  386   88]
[ 97  79 220  79  95  98]
[1245 2987 1239  337]
[ 37 699 495  35]
[ 85 144 319   2 167 168]
[ 75 220  74  76 711  96  76]
[ 73 281 476 281]
[2447]
[  61   62   64  429  274 1377]
[180 181 182 183 1

[ 458  858   30 1601  482 1106   85    9    8  128  433   85  498  144
  499]
[  52  206  634 1436]
[391 189 475 190 188 475 281  77  78 281 280  85  77  79 187 549 195 196
 189 317 195 190 188 475 361  77  75 196 189 317 475 196 476  77  97 359
 194 281 281 361]
[1041  482 1758  432]
[ 85 151]
[ 258  173 2998  718 1926]
[451 325  56 256 257 128  86 129 129 129   8 128 130]
[2378  887 1470  919   77  821   22]
[ 184    0 1588   19]
[141]
[692 451 529 643 918 275 783]
[ 96 549 188 189 359 193  77 351 475 361 361 195 476  77 281 147  77  95
 194 189 190 475]
[ 71 173  79]
[ 95  73  72  78  74  77  79 351  79  81 711  81  72 146  73  98  77 711
  74  78 357]
[461  47 185 642 467 386 101  55 184  24  25]
[ 323  536 1707]
[ 72 146  74]
[1069  165]
[76 96 78 96]
[ 365    5  691  669   64 1860   64]
[ 111 1341]
[ 97  73  74  78 146  73  74  72  74  78 701  72  79  81 146  96  78 146
  97  72]
[ 64 642  64 159  64 117 311]
[ 328 1688  462  212]
[ 73  72  78  73 219  74]
[593 401 261]
[2999   6

[  35   36  725  241  363  376 1431]
[165  44  45]
[349 230  33 601]
[1111  239]
[109 654 241 482]
[518 201 340 213]
[ 72 350  79  74 220  74 484 711]
[ 529 1351 1732   18]
[1625  638  608]
[45 57]
[ 604 1435]
[553 168]
[ 662  663  878 1035]
[ 93 354 271 355 240]
[359 475 196 282]
[  99   49  339  634 1015  213 1825]
[ 347 1848  134]
[475 190 282 476]
[1611  229  206 1281]
[97]
[ 95 281 361 475]
[ 75  96 220  76  77  98  72 484  79]
[ 323  536 1707]
[  39  839 1305  365  401  379  518  319 2063]
[1211 1052]
[146  74  78  97  96]
[ 8 86 85]
[ 554  596  110  316  799  596 1247  444  316 3008  482   91]
[1322 1688]
[ 93 354 424 248 207]
[2228    7  827  433  662  498  940   30  530  528  261 1669 1123  379
  700]
[137 435 363  15]
[1064  343]
[ 643  901  319 1229  380]
[231 249 990 210 263 383]
[78]
[ 449 1281  853  507]
[239 409 633 257   8  85 280 131 152 513 281 361]
[ 308  287 2312]
[ 36 291]
[174 175]
[ 59 761 169 679]
[241  38 496]
[ 75 220  74  76 711  96  76]
[ 131    9    9 1038 

[  92   93   94  900 1607  105  634]
[97 79 95 81 79 98]
[ 85   9 484]
[ 181  182 1066  379  756    3]
[217 663]
[146  96 350  72 351  74]
[1021  442]
[ 97 357 350]
[585 683 327]
[282   9  86 475   9 128 130  85]
[ 720  111 1946]
[ 251  378  584 2756]
[ 35 376]
[2543 2982]
[81]
[ 98  97 146]
[ 411  412   19 1303   56   57   64   65   66   67]
[76 72 97 73 72 96 78]
[ 36 507 988]
[173  72 146  73  98]
[128]
[509 729]
[41]
[  8 130   8 128 130  85 258   8   8 130 130]
[ 123  470  463 1936  529    8  130  129]
[1815  231  741  357   98  351 1017  215   42]
[ 200 1059   36  204  379  246  184 1014  197  231  316]
[ 667 1164 1111  536]
[  49  455 2238 1343  940   56  167  168  453]
[ 97 219  77 566  72  77  76  74  78  77 173  74  77 173  72  74  78]
[319   2]
[492 130 128]
[ 101  216  159 1331  231  270  726  231  710  463  257 1087  570]
[414  38]
[ 241 1253]
[550  62 789 168 217 238]
[240 550]
[553 168  82 664]
[ 150  150 1011  791 1111  239  608]
[ 125 1077  848  497  534 1625 2816]
[  

[790 607 227 804  24  25]
[ 657 1279]
[109 899]
[ 101  216   30 1272  109  396  241 1428]
[ 74 196 193 195 190 475 361]
[ 79 391  72  98]
[74]
[1134  694]
[956 102 253]
[85  4]
[718 987 467]
[470]
[ 536 1453  174  275]
[ 376 1431 1014 1605  252  502   35   36]
[ 241   31  638  294 1090  111  174  275]
[108 548 111]
[1639 2478 1055  841]
[2258 1067]
[ 101  216  204  101   55  295  714  204   23  213 1466 1281  504]
[736]
[ 80 219  95  73  74  78 146 701 219  77  97  73  96 219  76  72 220 219
 566  72  79  77  95  96 484 484 219  78  72  98  76  77  73  79  74 220
  98  73  77  97  79  81 351  72  95  79  77  95  79  78  98  79  81]
[1554 2502 2503   30  339  166 1447 3024]
[1276 1277    6  213  106]
[176  66 482 302]
[ 86 129   9   9  77  85   8 131   8]
[96 95 96 95 96]
[  8 128 258]
[   8  131  151   85 1123]
[101 216 408  50 429 101  55 988]
[ 95 475 717 195]
[319 239  15 199 311]
[ 672 3025  461  482]
[121 460 536 148 714]
[ 134   28 1661 1209  315  379 1302]
[1489 1490]
[1366  186

[176 177  40 274   8  86 128]
[ 85 144]
[1097  518  817 1537  775  179]
[ 95  73  72  78  79  97  79  77  97  98  96  78  79  77 484 219  97  79
 219 484  77  96 173  77  80 219  73  74  78]
[216 940 432 773 338 482]
[1671  433    2    3  278  453]
[346]
[767   5 770  57]
[ 40 272 104]
[   5   33   99   77  231  125 1164   51   77 2243   99   40  204]
[24]
[2073   21  516]
[711  74  78 357  77  96 173  77  95  73  72  78  74]
[  8 215  42]
[  27  168 1648 2036]
[305 308 601]
[141]
[  24  808  379  246 1133  518   49]
[173  79  74  98 219  81  79 350  72  81  96  78  77  97  98  79  74 357]
[ 184  151 1679  375   21  378 1251  378   64  223 2078  316  106  414
  311  887]
[71 98 96]
[ 75  73  72 220  72  75  97]
[921 753  33 482]
[ 155 1124]
[97]
[ 41 813 239]
[741 109]
[ 346  619  234 1331   83  379  315  637  424  349  230   30   39]
[ 86 280 131]
[2433  516]
[1665   67]
[567 350 386  86  98 484 258  86]
[ 756 1057 1072  813  239  744]
[ 95 194 189 190 475  77 484 281 722 189 361 195]

[382]
[531 103 179 932]
[95 73 72 78 74]
[ 97 549 475 189 190  77 193 188 476 361 195]
[492 130  86]
[2228    7  382 1080  457  159   25  473  382]
[339 496 144 258 151 913  77 104]
[484 391 131]
[ 756 1425  396 1425]
[652 330 353]
[195 359 281 361 281 192 196 195]
[ 97  74 220  79]
[ 235 1008  720  507]
[ 73 220]
[266 665]
[317 195 317 281 196 189 195 193]
[1933 1243 1866]
[ 121  585   60  150 1353]
[  24  714 1212  376   35   48  270]
[493 261 421]
[  0  23 213 870 450]
[231 612  70]
[ 639  634 1054  241  530  241]
[101 216 720 107]
[ 73 220  74]
[166  30 637 424 230]
[1974 2043   31   85  173]
[141]
[1313  901 1017  515]
[ 134 1974  414  699  689]
[ 86   9   9 151]
[  8 130 258   9 129   8 128  85 144   8 129]
[ 98  79 220   9  85 129]
[1054 1037  444 1016  320]
[909 240]
[653 654 337]
[45 45]
[  60 1055  333  861   63 1504  745  315 1066  262 1127  320   65  776
  346  257   60   85  503   63]
[351 189 190 282 475]
[130   8 152]
[ 80  74  78 350  74  77  75 220  74  71  74]
[ 17  1

[409 377 744]
[1992  421 1307  887]
[1042  278]
[ 85   8 144 129]
[530 156  56 256 257]
[ 95  96 484 711  72  78  74  98  72  96  78]
[1013  261   44   45]
[1213  482  303  279]
[ 414  240  562 2248   30  241  118]
[  88  262 1852  709]
[1203  106]
[ 97  98  74  98  79  77 146  81  72 350]
[ 86  85 144 131   9   8 131  86]
[  8   9  66 794 384 462]
[ 85 144]
[ 78 219  95 351 351  98]
[502 421]
[181 324 770]
[ 134  315 1111 2200   62  102]
[382  54 981]
[241 109 479 876]
[231 249 990]
[181 182]
[ 669  948 2333  629  291  750]
[948 174 257 278 453  77 105 276 169]
[  70 2996   12 1915 2297   37  311   30  120 3050  409 1899   33 1798
  404]
[1033  166  612]
[350 196 475 191 281 190]
[530]
[ 286  908  824 1181]
[1056 1607]
[1895  714]
[2068 2749 1230   30   18  424  818   30  255 2164  863  844  396  576
 1913  404]
[ 24  49 389]
[  58 1834  692 1970   58  146  189  190  717  191  281  475  359  195
  475  195]
[208   5]
[137 858 918 477 727 943   4 602 944]
[167 168   2 903 257  86 257  